version: '3'

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    image: image-server 
    container_name: server-container
    ports:
      - "5000:5000"
    working_dir: /usr/src/app
    command: ["npm", "run", "dev"]
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules


  client:
    build: 
        context: ./client
        dockerfile: Dockerfile
    image: image-client 
    container_name: client-container
    ports:
      - "5173:5173"
    working_dir: /usr/src/app
    command: ["npm", "run", "dev"]
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules