name: continuos_integration

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  server-tests:
    runs-on: ubuntu-latest
    name: Running unit tests on server side
    steps:
      - uses: actions/checkout@v2
        name: "checkout repository"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: "Install Dependencies"
        working-directory: server
        run: npm install

      - name: "run tests"
        working-directory: server
        run: npm run test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push server Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: zabdessamad/social-media:server-latest

      - name: Build and push client Docker image 
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: zabdessamad/social-media:client-latest